services:

  coordinator-server:
    image: apache/fluss:0.9.0-incubating
    command: coordinatorServer
    depends_on:
      - zookeeper
    networks:
      demo-net:
    environment:
      - |
        FLUSS_PROPERTIES=
        zookeeper.address: zookeeper:2181
        bind.listeners: INTERNAL://coordinator-server:0, CLIENT://coordinator-server:9123
        advertised.listeners: CLIENT://coordinator-server:9123
        internal.listener.name: INTERNAL
        remote.data.dir: /tmp/fluss/remote-data
        security.protocol.map: CLIENT:SASL, INTERNAL:PLAINTEXT
        security.sasl.enabled.mechanisms: PLAIN
        security.sasl.plain.jaas.config: org.apache.fluss.security.auth.sasl.plain.PlainLoginModule required user_admin="admin-pass" user_developer="developer-pass" ;
        super.users: User:admin        
    ports:
      - "9123:9123"
  tablet-server:
    image: apache/fluss:0.9.0-incubating
    command: tabletServer
    depends_on:
      - coordinator-server
    networks:
      demo-net:
    environment:
      - |
        FLUSS_PROPERTIES=
        zookeeper.address: zookeeper:2181
        bind.listeners: INTERNAL://tablet-server:0, CLIENT://tablet-server:9123
        advertised.listeners: CLIENT://tablet-server:9123
        internal.listener.name: INTERNAL
        tablet-server.id: 0
        kv.snapshot.interval: 0s
        data.dir: /tmp/fluss/data
        remote.data.dir: /tmp/fluss/remote-data
        security.protocol.map: CLIENT:SASL, INTERNAL:PLAINTEXT
        security.sasl.enabled.mechanisms: PLAIN
        security.sasl.plain.jaas.config: org.apache.fluss.security.auth.sasl.plain.PlainLoginModule required user_admin="admin-pass" user_developer="developer-pass" ;
        super.users: User:admin        

  zookeeper:
    restart: always
    image: zookeeper:3.9.2
    networks:
      demo-net:


  postgres:
    image: postgres:14.5
    container_name: db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      demo-net:
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
      - "-c"
      - "max_replication_slots=5"
      - "-c"
      - "max_wal_senders=5"
      - "-c"
      - "hot_standby=on"



  jobmanager:
      build: 
        context: .
        dockerfile: Dockerfile
      hostname: jobmanager
      container_name: jobmanager
      networks:
          demo-net:
      ports:
        - "8082:8081"
      command: jobmanager

      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8081/overview"]
        start_period: 30s
        interval: 5s
        timeout: 3s
        retries: 5
      environment:
        FLINK_PROPERTIES: |
          jobmanager.rpc.address: jobmanager
          taskmanager.numberOfTaskSlots: 4
          parallelism.default: 2


  taskmanager:
    build: 
      context: .
      dockerfile: Dockerfile
    hostname: taskmanager
    command: taskmanager
    container_name: taskmanager
    depends_on:
      jobmanager:
        condition: service_healthy  

    networks:
       demo-net:
    environment:
      FLINK_PROPERTIES: |
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 4
        parallelism.default: 2



networks:
   demo-net:


volumes:
  postgres_data:

